PACKAGE_NAME="mali-valhall-g610"
PACKAGE_VERSION="g29p1"
CLEAN="make clean KERNEL_SRC=${kernel_source_dir}"
MAKE[0]="make all KERNEL_SRC=${kernel_source_dir}"
BUILT_MODULE_NAME[0]="valhall_kbase"
BUILT_MODULE_LOCATION[0]="drivers/gpu/arm/valhall/"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
